// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/messages.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ticket struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Properties           *any.Any           `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	Dargs                map[string]float64 `protobuf:"bytes,3,rep,name=dargs,proto3" json:"dargs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	Sargs                map[string]string  `protobuf:"bytes,4,rep,name=sargs,proto3" json:"sargs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Ticket) Reset()         { *m = Ticket{} }
func (m *Ticket) String() string { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()    {}
func (*Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9fb1f207fd5b8c, []int{0}
}

func (m *Ticket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ticket.Unmarshal(m, b)
}
func (m *Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ticket.Marshal(b, m, deterministic)
}
func (m *Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket.Merge(m, src)
}
func (m *Ticket) XXX_Size() int {
	return xxx_messageInfo_Ticket.Size(m)
}
func (m *Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket proto.InternalMessageInfo

func (m *Ticket) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Ticket) GetProperties() *any.Any {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Ticket) GetDargs() map[string]float64 {
	if m != nil {
		return m.Dargs
	}
	return nil
}

func (m *Ticket) GetSargs() map[string]string {
	if m != nil {
		return m.Sargs
	}
	return nil
}

type Assignment struct {
	Connection           string   `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	Properties           *any.Any `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ClientUpdateRequired bool     `protobuf:"varint,4,opt,name=client_update_required,json=clientUpdateRequired,proto3" json:"client_update_required,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Assignment) Reset()         { *m = Assignment{} }
func (m *Assignment) String() string { return proto.CompactTextString(m) }
func (*Assignment) ProtoMessage()    {}
func (*Assignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9fb1f207fd5b8c, []int{1}
}

func (m *Assignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Assignment.Unmarshal(m, b)
}
func (m *Assignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Assignment.Marshal(b, m, deterministic)
}
func (m *Assignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Assignment.Merge(m, src)
}
func (m *Assignment) XXX_Size() int {
	return xxx_messageInfo_Assignment.Size(m)
}
func (m *Assignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Assignment.DiscardUnknown(m)
}

var xxx_messageInfo_Assignment proto.InternalMessageInfo

func (m *Assignment) GetConnection() string {
	if m != nil {
		return m.Connection
	}
	return ""
}

func (m *Assignment) GetProperties() *any.Any {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Assignment) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Assignment) GetClientUpdateRequired() bool {
	if m != nil {
		return m.ClientUpdateRequired
	}
	return false
}

type Query struct {
	Filters              []*Filter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9fb1f207fd5b8c, []int{2}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetFilters() []*Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

type StatsQuery struct {
	Query                *Query   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Dargs                []string `protobuf:"bytes,2,rep,name=dargs,proto3" json:"dargs,omitempty"`
	Sargs                []string `protobuf:"bytes,3,rep,name=sargs,proto3" json:"sargs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsQuery) Reset()         { *m = StatsQuery{} }
func (m *StatsQuery) String() string { return proto.CompactTextString(m) }
func (*StatsQuery) ProtoMessage()    {}
func (*StatsQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9fb1f207fd5b8c, []int{3}
}

func (m *StatsQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsQuery.Unmarshal(m, b)
}
func (m *StatsQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsQuery.Marshal(b, m, deterministic)
}
func (m *StatsQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsQuery.Merge(m, src)
}
func (m *StatsQuery) XXX_Size() int {
	return xxx_messageInfo_StatsQuery.Size(m)
}
func (m *StatsQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsQuery.DiscardUnknown(m)
}

var xxx_messageInfo_StatsQuery proto.InternalMessageInfo

func (m *StatsQuery) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *StatsQuery) GetDargs() []string {
	if m != nil {
		return m.Dargs
	}
	return nil
}

func (m *StatsQuery) GetSargs() []string {
	if m != nil {
		return m.Sargs
	}
	return nil
}

type StatsResponse struct {
	// Each column is in the order speicified in the query.  The tickets are ordered
	// in the same in each column.
	Dcolumn              []*StatsResponse_DoubleColumn `protobuf:"bytes,1,rep,name=dcolumn,proto3" json:"dcolumn,omitempty"`
	Scolumn              []*StatsResponse_StringColumn `protobuf:"bytes,2,rep,name=scolumn,proto3" json:"scolumn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *StatsResponse) Reset()         { *m = StatsResponse{} }
func (m *StatsResponse) String() string { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()    {}
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9fb1f207fd5b8c, []int{4}
}

func (m *StatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsResponse.Unmarshal(m, b)
}
func (m *StatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsResponse.Marshal(b, m, deterministic)
}
func (m *StatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsResponse.Merge(m, src)
}
func (m *StatsResponse) XXX_Size() int {
	return xxx_messageInfo_StatsResponse.Size(m)
}
func (m *StatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatsResponse proto.InternalMessageInfo

func (m *StatsResponse) GetDcolumn() []*StatsResponse_DoubleColumn {
	if m != nil {
		return m.Dcolumn
	}
	return nil
}

func (m *StatsResponse) GetScolumn() []*StatsResponse_StringColumn {
	if m != nil {
		return m.Scolumn
	}
	return nil
}

type StatsResponse_DoubleColumn struct {
	Darg                 string    `protobuf:"bytes,1,opt,name=darg,proto3" json:"darg,omitempty"`
	Value                []float64 `protobuf:"fixed64,2,rep,packed,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *StatsResponse_DoubleColumn) Reset()         { *m = StatsResponse_DoubleColumn{} }
func (m *StatsResponse_DoubleColumn) String() string { return proto.CompactTextString(m) }
func (*StatsResponse_DoubleColumn) ProtoMessage()    {}
func (*StatsResponse_DoubleColumn) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9fb1f207fd5b8c, []int{4, 0}
}

func (m *StatsResponse_DoubleColumn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsResponse_DoubleColumn.Unmarshal(m, b)
}
func (m *StatsResponse_DoubleColumn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsResponse_DoubleColumn.Marshal(b, m, deterministic)
}
func (m *StatsResponse_DoubleColumn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsResponse_DoubleColumn.Merge(m, src)
}
func (m *StatsResponse_DoubleColumn) XXX_Size() int {
	return xxx_messageInfo_StatsResponse_DoubleColumn.Size(m)
}
func (m *StatsResponse_DoubleColumn) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsResponse_DoubleColumn.DiscardUnknown(m)
}

var xxx_messageInfo_StatsResponse_DoubleColumn proto.InternalMessageInfo

func (m *StatsResponse_DoubleColumn) GetDarg() string {
	if m != nil {
		return m.Darg
	}
	return ""
}

func (m *StatsResponse_DoubleColumn) GetValue() []float64 {
	if m != nil {
		return m.Value
	}
	return nil
}

type StatsResponse_StringColumn struct {
	Sarg                 string    `protobuf:"bytes,1,opt,name=sarg,proto3" json:"sarg,omitempty"`
	String_              []float64 `protobuf:"fixed64,2,rep,packed,name=string,proto3" json:"string,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *StatsResponse_StringColumn) Reset()         { *m = StatsResponse_StringColumn{} }
func (m *StatsResponse_StringColumn) String() string { return proto.CompactTextString(m) }
func (*StatsResponse_StringColumn) ProtoMessage()    {}
func (*StatsResponse_StringColumn) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9fb1f207fd5b8c, []int{4, 1}
}

func (m *StatsResponse_StringColumn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsResponse_StringColumn.Unmarshal(m, b)
}
func (m *StatsResponse_StringColumn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsResponse_StringColumn.Marshal(b, m, deterministic)
}
func (m *StatsResponse_StringColumn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsResponse_StringColumn.Merge(m, src)
}
func (m *StatsResponse_StringColumn) XXX_Size() int {
	return xxx_messageInfo_StatsResponse_StringColumn.Size(m)
}
func (m *StatsResponse_StringColumn) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsResponse_StringColumn.DiscardUnknown(m)
}

var xxx_messageInfo_StatsResponse_StringColumn proto.InternalMessageInfo

func (m *StatsResponse_StringColumn) GetSarg() string {
	if m != nil {
		return m.Sarg
	}
	return ""
}

func (m *StatsResponse_StringColumn) GetString_() []float64 {
	if m != nil {
		return m.String_
	}
	return nil
}

type Filter struct {
	// Types that are valid to be assigned to Value:
	//	*Filter_StringFilter
	//	*Filter_DoubleFilter
	//	*Filter_PoolIndex
	Value                isFilter_Value `protobuf_oneof:"value"`
	IndexTimeoutSeconds  int32          `protobuf:"varint,1,opt,name=index_timeout_seconds,json=indexTimeoutSeconds,proto3" json:"index_timeout_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9fb1f207fd5b8c, []int{5}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

type isFilter_Value interface {
	isFilter_Value()
}

type Filter_StringFilter struct {
	StringFilter *StringFilter `protobuf:"bytes,2,opt,name=string_filter,json=stringFilter,proto3,oneof"`
}

type Filter_DoubleFilter struct {
	DoubleFilter *DoubleFilter `protobuf:"bytes,3,opt,name=double_filter,json=doubleFilter,proto3,oneof"`
}

type Filter_PoolIndex struct {
	PoolIndex *PoolIndex `protobuf:"bytes,4,opt,name=pool_index,json=poolIndex,proto3,oneof"`
}

func (*Filter_StringFilter) isFilter_Value() {}

func (*Filter_DoubleFilter) isFilter_Value() {}

func (*Filter_PoolIndex) isFilter_Value() {}

func (m *Filter) GetValue() isFilter_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Filter) GetStringFilter() *StringFilter {
	if x, ok := m.GetValue().(*Filter_StringFilter); ok {
		return x.StringFilter
	}
	return nil
}

func (m *Filter) GetDoubleFilter() *DoubleFilter {
	if x, ok := m.GetValue().(*Filter_DoubleFilter); ok {
		return x.DoubleFilter
	}
	return nil
}

func (m *Filter) GetPoolIndex() *PoolIndex {
	if x, ok := m.GetValue().(*Filter_PoolIndex); ok {
		return x.PoolIndex
	}
	return nil
}

func (m *Filter) GetIndexTimeoutSeconds() int32 {
	if m != nil {
		return m.IndexTimeoutSeconds
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Filter) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Filter_StringFilter)(nil),
		(*Filter_DoubleFilter)(nil),
		(*Filter_PoolIndex)(nil),
	}
}

type StringFilter struct {
	// Index Parameters
	Sarg string `protobuf:"bytes,1,opt,name=sarg,proto3" json:"sarg,omitempty"`
	// Query Parameters
	//
	// Types that are valid to be assigned to FilterMethod:
	//	*StringFilter_Equals
	//	*StringFilter_InSet
	//	*StringFilter_Contains
	FilterMethod isStringFilter_FilterMethod `protobuf_oneof:"filter_method"`
	// Finds all of the string that aren't included by the filter method instead.
	Invert               bool     `protobuf:"varint,5,opt,name=invert,proto3" json:"invert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringFilter) Reset()         { *m = StringFilter{} }
func (m *StringFilter) String() string { return proto.CompactTextString(m) }
func (*StringFilter) ProtoMessage()    {}
func (*StringFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9fb1f207fd5b8c, []int{6}
}

func (m *StringFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringFilter.Unmarshal(m, b)
}
func (m *StringFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringFilter.Marshal(b, m, deterministic)
}
func (m *StringFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringFilter.Merge(m, src)
}
func (m *StringFilter) XXX_Size() int {
	return xxx_messageInfo_StringFilter.Size(m)
}
func (m *StringFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_StringFilter.DiscardUnknown(m)
}

var xxx_messageInfo_StringFilter proto.InternalMessageInfo

func (m *StringFilter) GetSarg() string {
	if m != nil {
		return m.Sarg
	}
	return ""
}

type isStringFilter_FilterMethod interface {
	isStringFilter_FilterMethod()
}

type StringFilter_Equals struct {
	Equals string `protobuf:"bytes,2,opt,name=equals,proto3,oneof"`
}

type StringFilter_InSet struct {
	InSet *StringSet `protobuf:"bytes,3,opt,name=in_set,json=inSet,proto3,oneof"`
}

type StringFilter_Contains struct {
	Contains string `protobuf:"bytes,4,opt,name=contains,proto3,oneof"`
}

func (*StringFilter_Equals) isStringFilter_FilterMethod() {}

func (*StringFilter_InSet) isStringFilter_FilterMethod() {}

func (*StringFilter_Contains) isStringFilter_FilterMethod() {}

func (m *StringFilter) GetFilterMethod() isStringFilter_FilterMethod {
	if m != nil {
		return m.FilterMethod
	}
	return nil
}

func (m *StringFilter) GetEquals() string {
	if x, ok := m.GetFilterMethod().(*StringFilter_Equals); ok {
		return x.Equals
	}
	return ""
}

func (m *StringFilter) GetInSet() *StringSet {
	if x, ok := m.GetFilterMethod().(*StringFilter_InSet); ok {
		return x.InSet
	}
	return nil
}

func (m *StringFilter) GetContains() string {
	if x, ok := m.GetFilterMethod().(*StringFilter_Contains); ok {
		return x.Contains
	}
	return ""
}

func (m *StringFilter) GetInvert() bool {
	if m != nil {
		return m.Invert
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StringFilter) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StringFilter_Equals)(nil),
		(*StringFilter_InSet)(nil),
		(*StringFilter_Contains)(nil),
	}
}

type StringSet struct {
	Value                []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringSet) Reset()         { *m = StringSet{} }
func (m *StringSet) String() string { return proto.CompactTextString(m) }
func (*StringSet) ProtoMessage()    {}
func (*StringSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9fb1f207fd5b8c, []int{7}
}

func (m *StringSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringSet.Unmarshal(m, b)
}
func (m *StringSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringSet.Marshal(b, m, deterministic)
}
func (m *StringSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringSet.Merge(m, src)
}
func (m *StringSet) XXX_Size() int {
	return xxx_messageInfo_StringSet.Size(m)
}
func (m *StringSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StringSet.DiscardUnknown(m)
}

var xxx_messageInfo_StringSet proto.InternalMessageInfo

func (m *StringSet) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type DoubleFilter struct {
	// Index Parameters
	Darg string `protobuf:"bytes,1,opt,name=darg,proto3" json:"darg,omitempty"`
	// Query Parameters
	Min                  float64  `protobuf:"fixed64,2,opt,name=min,proto3" json:"min,omitempty"`
	Max                  float64  `protobuf:"fixed64,3,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoubleFilter) Reset()         { *m = DoubleFilter{} }
func (m *DoubleFilter) String() string { return proto.CompactTextString(m) }
func (*DoubleFilter) ProtoMessage()    {}
func (*DoubleFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9fb1f207fd5b8c, []int{8}
}

func (m *DoubleFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleFilter.Unmarshal(m, b)
}
func (m *DoubleFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleFilter.Marshal(b, m, deterministic)
}
func (m *DoubleFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleFilter.Merge(m, src)
}
func (m *DoubleFilter) XXX_Size() int {
	return xxx_messageInfo_DoubleFilter.Size(m)
}
func (m *DoubleFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleFilter.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleFilter proto.InternalMessageInfo

func (m *DoubleFilter) GetDarg() string {
	if m != nil {
		return m.Darg
	}
	return ""
}

func (m *DoubleFilter) GetMin() float64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *DoubleFilter) GetMax() float64 {
	if m != nil {
		return m.Max
	}
	return 0
}

// This "index" merely keeps track of all of the tickets which match the
// preceding filters.  Instead of finding the tickets which match at query
// time, this finds them when tickets are added to the system, and merely
// returns the existing slice at query time.
type PoolIndex struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoolIndex) Reset()         { *m = PoolIndex{} }
func (m *PoolIndex) String() string { return proto.CompactTextString(m) }
func (*PoolIndex) ProtoMessage()    {}
func (*PoolIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9fb1f207fd5b8c, []int{9}
}

func (m *PoolIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoolIndex.Unmarshal(m, b)
}
func (m *PoolIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoolIndex.Marshal(b, m, deterministic)
}
func (m *PoolIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolIndex.Merge(m, src)
}
func (m *PoolIndex) XXX_Size() int {
	return xxx_messageInfo_PoolIndex.Size(m)
}
func (m *PoolIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolIndex.DiscardUnknown(m)
}

var xxx_messageInfo_PoolIndex proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Ticket)(nil), "api.Ticket")
	proto.RegisterMapType((map[string]float64)(nil), "api.Ticket.DargsEntry")
	proto.RegisterMapType((map[string]string)(nil), "api.Ticket.SargsEntry")
	proto.RegisterType((*Assignment)(nil), "api.Assignment")
	proto.RegisterType((*Query)(nil), "api.Query")
	proto.RegisterType((*StatsQuery)(nil), "api.StatsQuery")
	proto.RegisterType((*StatsResponse)(nil), "api.StatsResponse")
	proto.RegisterType((*StatsResponse_DoubleColumn)(nil), "api.StatsResponse.DoubleColumn")
	proto.RegisterType((*StatsResponse_StringColumn)(nil), "api.StatsResponse.StringColumn")
	proto.RegisterType((*Filter)(nil), "api.Filter")
	proto.RegisterType((*StringFilter)(nil), "api.StringFilter")
	proto.RegisterType((*StringSet)(nil), "api.StringSet")
	proto.RegisterType((*DoubleFilter)(nil), "api.DoubleFilter")
	proto.RegisterType((*PoolIndex)(nil), "api.PoolIndex")
}

func init() { proto.RegisterFile("api/messages.proto", fileDescriptor_cb9fb1f207fd5b8c) }

var fileDescriptor_cb9fb1f207fd5b8c = []byte{
	// 716 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0x45, 0x53, 0xb6, 0x46, 0xb6, 0xeb, 0x6e, 0x55, 0x83, 0x15, 0x8a, 0x56, 0x25, 0x50,
	0x54, 0x87, 0x82, 0x02, 0x54, 0x1f, 0x54, 0xdf, 0xec, 0xba, 0x86, 0x72, 0x4b, 0x28, 0xe7, 0xe2,
	0x0b, 0x41, 0x89, 0x63, 0x65, 0x61, 0x6a, 0x97, 0xde, 0x5d, 0x1a, 0xd6, 0xcb, 0xe4, 0x09, 0x82,
	0x3c, 0x58, 0x5e, 0x21, 0x97, 0x60, 0x7f, 0x28, 0x31, 0x70, 0x02, 0x04, 0xb9, 0xed, 0xcc, 0xf7,
	0x7d, 0xb3, 0x33, 0xdf, 0x0e, 0x09, 0x24, 0x2b, 0xe9, 0x78, 0x8d, 0x52, 0x66, 0x2b, 0x94, 0x71,
	0x29, 0xb8, 0xe2, 0xc4, 0xcf, 0x4a, 0x3a, 0xf8, 0x65, 0xc5, 0xf9, 0xaa, 0xc0, 0xb1, 0x49, 0x2d,
	0xaa, 0xbb, 0x71, 0xc6, 0x36, 0x16, 0x8f, 0xde, 0xb6, 0xa1, 0x73, 0x43, 0x97, 0xf7, 0xa8, 0xc8,
	0x31, 0xb4, 0x69, 0x1e, 0x7a, 0x43, 0x6f, 0xd4, 0x4d, 0xda, 0x34, 0x27, 0x67, 0x00, 0xa5, 0xe0,
	0x25, 0x0a, 0x45, 0x51, 0x86, 0xed, 0xa1, 0x37, 0xea, 0x4d, 0xfa, 0xb1, 0x2d, 0x15, 0xd7, 0xa5,
	0xe2, 0x0b, 0xb6, 0x49, 0x1a, 0x3c, 0xf2, 0x37, 0x04, 0x79, 0x26, 0x56, 0x32, 0xf4, 0x87, 0xfe,
	0xa8, 0x37, 0x39, 0x8d, 0xb3, 0x92, 0xc6, 0xf6, 0x86, 0xf8, 0x4a, 0x03, 0xff, 0x33, 0x25, 0x36,
	0x89, 0x25, 0x69, 0xb6, 0x34, 0xec, 0xbd, 0xe7, 0xec, 0x79, 0x83, 0x6d, 0x48, 0x83, 0x29, 0xc0,
	0xae, 0x04, 0x39, 0x01, 0xff, 0x1e, 0x37, 0xae, 0x61, 0x7d, 0x24, 0x7d, 0x08, 0x1e, 0xb3, 0xa2,
	0x42, 0xd3, 0xac, 0x97, 0xd8, 0xe0, 0xbc, 0x3d, 0xf5, 0xb4, 0x72, 0xfe, 0xcd, 0xca, 0x6e, 0x43,
	0x19, 0xbd, 0xf7, 0x00, 0x2e, 0xa4, 0xa4, 0x2b, 0xb6, 0x46, 0xa6, 0xc8, 0x6f, 0x00, 0x4b, 0xce,
	0x18, 0x2e, 0x15, 0xe5, 0xcc, 0x55, 0x68, 0x64, 0xbe, 0xd3, 0xb4, 0x3e, 0x04, 0x28, 0x04, 0x17,
	0xa1, 0x6f, 0xaf, 0x37, 0x01, 0x39, 0x83, 0xd3, 0x65, 0x41, 0x91, 0xa9, 0xb4, 0x2a, 0xf3, 0x4c,
	0x61, 0x2a, 0xf0, 0xa1, 0xa2, 0x02, 0xf3, 0x70, 0x6f, 0xe8, 0x8d, 0x0e, 0x92, 0xbe, 0x45, 0x5f,
	0x1b, 0x30, 0x71, 0x58, 0x14, 0x43, 0xf0, 0xaa, 0x42, 0xb1, 0x21, 0x7f, 0xc2, 0xfe, 0x1d, 0x2d,
	0x14, 0x0a, 0x19, 0x7a, 0xc6, 0xdd, 0x9e, 0x71, 0xf7, 0xda, 0xe4, 0x92, 0x1a, 0x8b, 0x6e, 0x01,
	0xe6, 0x2a, 0x53, 0xd2, 0x8a, 0x86, 0x10, 0x3c, 0xe8, 0x83, 0x19, 0xad, 0x37, 0x01, 0x23, 0x31,
	0x50, 0x62, 0x01, 0xdd, 0xab, 0x7d, 0xe0, 0xf6, 0xd0, 0xd7, 0xbd, 0xda, 0x87, 0xec, 0xd7, 0x0f,
	0xe9, 0xdb, 0xac, 0x09, 0xa2, 0x8f, 0x1e, 0x1c, 0x99, 0xe2, 0x09, 0xca, 0x92, 0x33, 0x89, 0xe4,
	0x5f, 0xd8, 0xcf, 0x97, 0xbc, 0xa8, 0xd6, 0xcc, 0x35, 0xf5, 0xbb, 0xb9, 0xe1, 0x33, 0x52, 0x7c,
	0xc5, 0xab, 0x45, 0x81, 0xff, 0x19, 0x5a, 0x52, 0xf3, 0xb5, 0x54, 0x3a, 0x69, 0xfb, 0xab, 0xd2,
	0xb9, 0x12, 0x94, 0xad, 0x6a, 0xa9, 0xe3, 0x0f, 0xa6, 0x70, 0xd8, 0xac, 0x49, 0x08, 0xec, 0xe9,
	0xb6, 0xdd, 0xfb, 0x99, 0x73, 0x73, 0x05, 0xfc, 0xed, 0xf2, 0x0c, 0xce, 0xe1, 0xb0, 0x59, 0x52,
	0x2b, 0x65, 0x43, 0xa9, 0xcf, 0xe4, 0x14, 0x3a, 0xd2, 0x70, 0x9c, 0xd4, 0x45, 0xd1, 0x07, 0x0f,
	0x3a, 0xd6, 0x6d, 0x32, 0x85, 0x23, 0x9b, 0x4c, 0xad, 0xed, 0x6e, 0x33, 0x7e, 0x74, 0x13, 0x68,
	0xc4, 0x32, 0x67, 0xad, 0xe4, 0x50, 0x36, 0x62, 0xad, 0xcc, 0x4d, 0xeb, 0xb5, 0xd2, 0x6f, 0x28,
	0xed, 0x50, 0x3b, 0x65, 0xde, 0x88, 0xc9, 0x18, 0xa0, 0xe4, 0xbc, 0x48, 0x29, 0xcb, 0xf1, 0xc9,
	0xac, 0x4c, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x39, 0x2f, 0x5e, 0xe8, 0xec, 0xac, 0x95, 0x74, 0xcb,
	0x3a, 0x20, 0x13, 0xf8, 0xd9, 0x70, 0x53, 0x45, 0xd7, 0xc8, 0x2b, 0x95, 0x4a, 0x5c, 0x72, 0x96,
	0x4b, 0x33, 0x6c, 0x90, 0xfc, 0x64, 0xc0, 0x1b, 0x8b, 0xcd, 0x2d, 0x74, 0xb9, 0xef, 0x5c, 0x8b,
	0xde, 0x79, 0xb5, 0x53, 0xee, 0xfa, 0x2f, 0x39, 0x15, 0x42, 0x07, 0x1f, 0xaa, 0xac, 0xb0, 0x5f,
	0x46, 0x77, 0xd6, 0x4a, 0x5c, 0x4c, 0xfe, 0x82, 0x0e, 0x65, 0xa9, 0x44, 0xe5, 0xe6, 0x3b, 0x6e,
	0x38, 0x33, 0x47, 0x35, 0x6b, 0x25, 0x01, 0x65, 0x73, 0x54, 0xe4, 0x57, 0x38, 0x58, 0x72, 0xa6,
	0x32, 0xca, 0xa4, 0x99, 0x49, 0x17, 0xd9, 0x66, 0xf4, 0x53, 0x50, 0xf6, 0x88, 0x42, 0x85, 0x81,
	0xf9, 0x44, 0x5c, 0x74, 0xf9, 0x03, 0x1c, 0x59, 0xfb, 0xd2, 0x35, 0xaa, 0x37, 0x3c, 0x8f, 0xfe,
	0x80, 0xee, 0xb6, 0xf8, 0xee, 0xe9, 0x3d, 0xbb, 0xbc, 0x76, 0xa2, 0xeb, 0x7a, 0x69, 0x76, 0x03,
	0x3d, 0x5b, 0x9a, 0x13, 0xf0, 0xd7, 0x94, 0xb9, 0xff, 0x8d, 0x3e, 0x9a, 0x4c, 0xf6, 0x64, 0xa6,
	0xd0, 0x99, 0xec, 0x29, 0xea, 0x41, 0x77, 0x6b, 0xf8, 0x65, 0xff, 0x96, 0x50, 0xa6, 0x50, 0xb0,
	0xac, 0x18, 0xdf, 0x55, 0xaa, 0x12, 0x38, 0x2e, 0x17, 0x8b, 0x8e, 0xf9, 0x33, 0xfc, 0xf3, 0x29,
	0x00, 0x00, 0xff, 0xff, 0xd2, 0x01, 0x12, 0x56, 0xc2, 0x05, 0x00, 0x00,
}
