// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/store.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
	pb "open-match.dev/open-match/pkg/pb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IndexUpdatesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexUpdatesRequest) Reset()         { *m = IndexUpdatesRequest{} }
func (m *IndexUpdatesRequest) String() string { return proto.CompactTextString(m) }
func (*IndexUpdatesRequest) ProtoMessage()    {}
func (*IndexUpdatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a710cb4b40b033c1, []int{0}
}

func (m *IndexUpdatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexUpdatesRequest.Unmarshal(m, b)
}
func (m *IndexUpdatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexUpdatesRequest.Marshal(b, m, deterministic)
}
func (m *IndexUpdatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexUpdatesRequest.Merge(m, src)
}
func (m *IndexUpdatesRequest) XXX_Size() int {
	return xxx_messageInfo_IndexUpdatesRequest.Size(m)
}
func (m *IndexUpdatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexUpdatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexUpdatesRequest proto.InternalMessageInfo

type IndexUpdatesResponse struct {
	AddedTickets         []*pb.Ticket `protobuf:"bytes,1,rep,name=added_tickets,json=addedTickets,proto3" json:"added_tickets,omitempty"`
	RemovedTicketIds     []string     `protobuf:"bytes,2,rep,name=removed_ticket_ids,json=removedTicketIds,proto3" json:"removed_ticket_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *IndexUpdatesResponse) Reset()         { *m = IndexUpdatesResponse{} }
func (m *IndexUpdatesResponse) String() string { return proto.CompactTextString(m) }
func (*IndexUpdatesResponse) ProtoMessage()    {}
func (*IndexUpdatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a710cb4b40b033c1, []int{1}
}

func (m *IndexUpdatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexUpdatesResponse.Unmarshal(m, b)
}
func (m *IndexUpdatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexUpdatesResponse.Marshal(b, m, deterministic)
}
func (m *IndexUpdatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexUpdatesResponse.Merge(m, src)
}
func (m *IndexUpdatesResponse) XXX_Size() int {
	return xxx_messageInfo_IndexUpdatesResponse.Size(m)
}
func (m *IndexUpdatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexUpdatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IndexUpdatesResponse proto.InternalMessageInfo

func (m *IndexUpdatesResponse) GetAddedTickets() []*pb.Ticket {
	if m != nil {
		return m.AddedTickets
	}
	return nil
}

func (m *IndexUpdatesResponse) GetRemovedTicketIds() []string {
	if m != nil {
		return m.RemovedTicketIds
	}
	return nil
}

type DeindexTicketRequest struct {
	TicketId             string   `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeindexTicketRequest) Reset()         { *m = DeindexTicketRequest{} }
func (m *DeindexTicketRequest) String() string { return proto.CompactTextString(m) }
func (*DeindexTicketRequest) ProtoMessage()    {}
func (*DeindexTicketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a710cb4b40b033c1, []int{2}
}

func (m *DeindexTicketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeindexTicketRequest.Unmarshal(m, b)
}
func (m *DeindexTicketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeindexTicketRequest.Marshal(b, m, deterministic)
}
func (m *DeindexTicketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeindexTicketRequest.Merge(m, src)
}
func (m *DeindexTicketRequest) XXX_Size() int {
	return xxx_messageInfo_DeindexTicketRequest.Size(m)
}
func (m *DeindexTicketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeindexTicketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeindexTicketRequest proto.InternalMessageInfo

func (m *DeindexTicketRequest) GetTicketId() string {
	if m != nil {
		return m.TicketId
	}
	return ""
}

type DeindexTicketResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeindexTicketResponse) Reset()         { *m = DeindexTicketResponse{} }
func (m *DeindexTicketResponse) String() string { return proto.CompactTextString(m) }
func (*DeindexTicketResponse) ProtoMessage()    {}
func (*DeindexTicketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a710cb4b40b033c1, []int{3}
}

func (m *DeindexTicketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeindexTicketResponse.Unmarshal(m, b)
}
func (m *DeindexTicketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeindexTicketResponse.Marshal(b, m, deterministic)
}
func (m *DeindexTicketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeindexTicketResponse.Merge(m, src)
}
func (m *DeindexTicketResponse) XXX_Size() int {
	return xxx_messageInfo_DeindexTicketResponse.Size(m)
}
func (m *DeindexTicketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeindexTicketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeindexTicketResponse proto.InternalMessageInfo

type CreateTicketRequest struct {
	Ticket               *pb.Ticket `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateTicketRequest) Reset()         { *m = CreateTicketRequest{} }
func (m *CreateTicketRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTicketRequest) ProtoMessage()    {}
func (*CreateTicketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a710cb4b40b033c1, []int{4}
}

func (m *CreateTicketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTicketRequest.Unmarshal(m, b)
}
func (m *CreateTicketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTicketRequest.Marshal(b, m, deterministic)
}
func (m *CreateTicketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTicketRequest.Merge(m, src)
}
func (m *CreateTicketRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTicketRequest.Size(m)
}
func (m *CreateTicketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTicketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTicketRequest proto.InternalMessageInfo

func (m *CreateTicketRequest) GetTicket() *pb.Ticket {
	if m != nil {
		return m.Ticket
	}
	return nil
}

type CreateTicketResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTicketResponse) Reset()         { *m = CreateTicketResponse{} }
func (m *CreateTicketResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTicketResponse) ProtoMessage()    {}
func (*CreateTicketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a710cb4b40b033c1, []int{5}
}

func (m *CreateTicketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTicketResponse.Unmarshal(m, b)
}
func (m *CreateTicketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTicketResponse.Marshal(b, m, deterministic)
}
func (m *CreateTicketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTicketResponse.Merge(m, src)
}
func (m *CreateTicketResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTicketResponse.Size(m)
}
func (m *CreateTicketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTicketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTicketResponse proto.InternalMessageInfo

type AssignTicketsRequest struct {
	TicketIds            []string `protobuf:"bytes,1,rep,name=ticket_ids,json=ticketIds,proto3" json:"ticket_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignTicketsRequest) Reset()         { *m = AssignTicketsRequest{} }
func (m *AssignTicketsRequest) String() string { return proto.CompactTextString(m) }
func (*AssignTicketsRequest) ProtoMessage()    {}
func (*AssignTicketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a710cb4b40b033c1, []int{6}
}

func (m *AssignTicketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignTicketsRequest.Unmarshal(m, b)
}
func (m *AssignTicketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignTicketsRequest.Marshal(b, m, deterministic)
}
func (m *AssignTicketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignTicketsRequest.Merge(m, src)
}
func (m *AssignTicketsRequest) XXX_Size() int {
	return xxx_messageInfo_AssignTicketsRequest.Size(m)
}
func (m *AssignTicketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignTicketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AssignTicketsRequest proto.InternalMessageInfo

func (m *AssignTicketsRequest) GetTicketIds() []string {
	if m != nil {
		return m.TicketIds
	}
	return nil
}

type AssignTicketsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignTicketsResponse) Reset()         { *m = AssignTicketsResponse{} }
func (m *AssignTicketsResponse) String() string { return proto.CompactTextString(m) }
func (*AssignTicketsResponse) ProtoMessage()    {}
func (*AssignTicketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a710cb4b40b033c1, []int{7}
}

func (m *AssignTicketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignTicketsResponse.Unmarshal(m, b)
}
func (m *AssignTicketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignTicketsResponse.Marshal(b, m, deterministic)
}
func (m *AssignTicketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignTicketsResponse.Merge(m, src)
}
func (m *AssignTicketsResponse) XXX_Size() int {
	return xxx_messageInfo_AssignTicketsResponse.Size(m)
}
func (m *AssignTicketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignTicketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AssignTicketsResponse proto.InternalMessageInfo

type AssignmentSubscribeRequest struct {
	TicketId             string   `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignmentSubscribeRequest) Reset()         { *m = AssignmentSubscribeRequest{} }
func (m *AssignmentSubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*AssignmentSubscribeRequest) ProtoMessage()    {}
func (*AssignmentSubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a710cb4b40b033c1, []int{8}
}

func (m *AssignmentSubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignmentSubscribeRequest.Unmarshal(m, b)
}
func (m *AssignmentSubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignmentSubscribeRequest.Marshal(b, m, deterministic)
}
func (m *AssignmentSubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignmentSubscribeRequest.Merge(m, src)
}
func (m *AssignmentSubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_AssignmentSubscribeRequest.Size(m)
}
func (m *AssignmentSubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignmentSubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AssignmentSubscribeRequest proto.InternalMessageInfo

func (m *AssignmentSubscribeRequest) GetTicketId() string {
	if m != nil {
		return m.TicketId
	}
	return ""
}

type AssignmentSubscribeResponse struct {
	TicketIds            []string       `protobuf:"bytes,1,rep,name=ticket_ids,json=ticketIds,proto3" json:"ticket_ids,omitempty"`
	Assignment           *pb.Assignment `protobuf:"bytes,2,opt,name=assignment,proto3" json:"assignment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AssignmentSubscribeResponse) Reset()         { *m = AssignmentSubscribeResponse{} }
func (m *AssignmentSubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*AssignmentSubscribeResponse) ProtoMessage()    {}
func (*AssignmentSubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a710cb4b40b033c1, []int{9}
}

func (m *AssignmentSubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignmentSubscribeResponse.Unmarshal(m, b)
}
func (m *AssignmentSubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignmentSubscribeResponse.Marshal(b, m, deterministic)
}
func (m *AssignmentSubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignmentSubscribeResponse.Merge(m, src)
}
func (m *AssignmentSubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_AssignmentSubscribeResponse.Size(m)
}
func (m *AssignmentSubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignmentSubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AssignmentSubscribeResponse proto.InternalMessageInfo

func (m *AssignmentSubscribeResponse) GetTicketIds() []string {
	if m != nil {
		return m.TicketIds
	}
	return nil
}

func (m *AssignmentSubscribeResponse) GetAssignment() *pb.Assignment {
	if m != nil {
		return m.Assignment
	}
	return nil
}

func init() {
	proto.RegisterType((*IndexUpdatesRequest)(nil), "api.IndexUpdatesRequest")
	proto.RegisterType((*IndexUpdatesResponse)(nil), "api.IndexUpdatesResponse")
	proto.RegisterType((*DeindexTicketRequest)(nil), "api.DeindexTicketRequest")
	proto.RegisterType((*DeindexTicketResponse)(nil), "api.DeindexTicketResponse")
	proto.RegisterType((*CreateTicketRequest)(nil), "api.CreateTicketRequest")
	proto.RegisterType((*CreateTicketResponse)(nil), "api.CreateTicketResponse")
	proto.RegisterType((*AssignTicketsRequest)(nil), "api.AssignTicketsRequest")
	proto.RegisterType((*AssignTicketsResponse)(nil), "api.AssignTicketsResponse")
	proto.RegisterType((*AssignmentSubscribeRequest)(nil), "api.AssignmentSubscribeRequest")
	proto.RegisterType((*AssignmentSubscribeResponse)(nil), "api.AssignmentSubscribeResponse")
}

func init() { proto.RegisterFile("api/store.proto", fileDescriptor_a710cb4b40b033c1) }

var fileDescriptor_a710cb4b40b033c1 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcf, 0xcf, 0xd2, 0x40,
	0x14, 0x4c, 0x69, 0x24, 0xf6, 0x01, 0xc1, 0x2c, 0x45, 0x6a, 0x89, 0xb1, 0xa9, 0x97, 0x1e, 0x0c,
	0x10, 0x88, 0x07, 0xbd, 0x29, 0x6a, 0xc2, 0xb5, 0xe8, 0xc5, 0x98, 0x90, 0x2d, 0x7d, 0x21, 0x1b,
	0xed, 0x0f, 0xbb, 0x0b, 0xf1, 0xea, 0x7f, 0x6e, 0xba, 0xbb, 0xf6, 0x6b, 0x9b, 0xfd, 0xbe, 0x7c,
	0x47, 0x76, 0xde, 0x0c, 0x33, 0x6f, 0x5e, 0x61, 0x4a, 0x4b, 0xb6, 0xe6, 0xa2, 0xa8, 0x70, 0x55,
	0x56, 0x85, 0x28, 0x88, 0x4d, 0x4b, 0xe6, 0x93, 0xfa, 0x35, 0x43, 0xce, 0xe9, 0x05, 0xb9, 0x02,
	0xc2, 0x39, 0xcc, 0x0e, 0x79, 0x8a, 0x7f, 0xbe, 0x95, 0x29, 0x15, 0xc8, 0x63, 0xfc, 0x7d, 0x45,
	0x2e, 0xc2, 0x1b, 0xb8, 0xdd, 0x67, 0x5e, 0x16, 0x39, 0x47, 0xb2, 0x81, 0x09, 0x4d, 0x53, 0x4c,
	0x4f, 0x82, 0x9d, 0x7f, 0xa2, 0xe0, 0x9e, 0x15, 0xd8, 0xd1, 0x68, 0x3b, 0x5a, 0xd1, 0x92, 0xad,
	0xbe, 0xca, 0xb7, 0x78, 0x2c, 0x27, 0xd4, 0x0f, 0x4e, 0xde, 0x00, 0xa9, 0x30, 0x2b, 0x6e, 0x0d,
	0xe7, 0xc4, 0x52, 0xee, 0x0d, 0x02, 0x3b, 0x72, 0xe2, 0x67, 0x1a, 0x51, 0xb3, 0x87, 0x94, 0x87,
	0x3b, 0x70, 0x3f, 0x21, 0xab, 0xff, 0x59, 0x8b, 0x29, 0x3f, 0x64, 0x09, 0x4e, 0xc3, 0xf6, 0xac,
	0xc0, 0x8a, 0x9c, 0xf8, 0xa9, 0xd0, 0xac, 0x70, 0x01, 0xf3, 0x1e, 0x49, 0xb9, 0x0d, 0xdf, 0xc3,
	0x6c, 0x5f, 0x21, 0x15, 0xd8, 0x15, 0x7b, 0x0d, 0x43, 0xc5, 0x95, 0x4a, 0x3d, 0xf7, 0x1a, 0x0a,
	0x9f, 0x83, 0xdb, 0xe5, 0x6a, 0xcd, 0xb7, 0xe0, 0x7e, 0xe0, 0x9c, 0x5d, 0x72, 0x1d, 0xf0, 0xbf,
	0xe8, 0x4b, 0x80, 0x56, 0x3e, 0x4b, 0xe6, 0x73, 0x44, 0x13, 0x6c, 0x01, 0xf3, 0x1e, 0x4d, 0xeb,
	0xbd, 0x03, 0x5f, 0x01, 0x19, 0xe6, 0xe2, 0x78, 0x4d, 0xf8, 0xb9, 0x62, 0x09, 0x3e, 0x2a, 0x77,
	0x06, 0x4b, 0x23, 0x55, 0x77, 0xf5, 0xb0, 0x23, 0xb2, 0x06, 0xa0, 0x0d, 0xdb, 0x1b, 0xc8, 0x4d,
	0x4c, 0xe5, 0x26, 0xee, 0x44, 0xe3, 0xd6, 0xc8, 0xf6, 0xaf, 0x0d, 0x4f, 0x8e, 0xf5, 0x4d, 0x91,
	0xcf, 0x30, 0x6e, 0x5f, 0x07, 0xf1, 0x24, 0xcd, 0x70, 0x47, 0xfe, 0x0b, 0x03, 0xa2, 0xec, 0x6d,
	0x2c, 0xf2, 0x05, 0x26, 0x9d, 0xde, 0x88, 0x9a, 0x36, 0x1d, 0x80, 0xef, 0x9b, 0x20, 0x1d, 0x74,
	0x0f, 0xe3, 0x76, 0x55, 0xda, 0x8e, 0xa1, 0x79, 0x6d, 0xc7, 0xd4, 0x6b, 0x6d, 0xa6, 0x53, 0x90,
	0x36, 0x63, 0xea, 0x5a, 0x9b, 0x31, 0xf6, 0x49, 0x7e, 0xc0, 0xcc, 0x50, 0x0a, 0x79, 0xd5, 0xdb,
	0x6c, 0xbf, 0x69, 0x3f, 0xb8, 0x7f, 0x40, 0x29, 0x47, 0xd6, 0xc6, 0xfa, 0x38, 0xf9, 0x3e, 0x62,
	0xb9, 0xc0, 0x2a, 0xa7, 0xbf, 0xd6, 0x65, 0x92, 0x0c, 0xe5, 0x47, 0xbc, 0xfb, 0x17, 0x00, 0x00,
	0xff, 0xff, 0x31, 0xce, 0xcc, 0xb0, 0xf0, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreClient interface {
	IndexUpdates(ctx context.Context, in *IndexUpdatesRequest, opts ...grpc.CallOption) (Store_IndexUpdatesClient, error)
	DeindexTicket(ctx context.Context, in *DeindexTicketRequest, opts ...grpc.CallOption) (*DeindexTicketResponse, error)
	CreateTicket(ctx context.Context, in *CreateTicketRequest, opts ...grpc.CallOption) (*CreateTicketResponse, error)
	AssignTickets(ctx context.Context, in *AssignTicketsRequest, opts ...grpc.CallOption) (*AssignTicketsResponse, error)
	AssignmentSubscribe(ctx context.Context, opts ...grpc.CallOption) (Store_AssignmentSubscribeClient, error)
}

type storeClient struct {
	cc *grpc.ClientConn
}

func NewStoreClient(cc *grpc.ClientConn) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) IndexUpdates(ctx context.Context, in *IndexUpdatesRequest, opts ...grpc.CallOption) (Store_IndexUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Store_serviceDesc.Streams[0], "/api.Store/IndexUpdates", opts...)
	if err != nil {
		return nil, err
	}
	x := &storeIndexUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Store_IndexUpdatesClient interface {
	Recv() (*IndexUpdatesResponse, error)
	grpc.ClientStream
}

type storeIndexUpdatesClient struct {
	grpc.ClientStream
}

func (x *storeIndexUpdatesClient) Recv() (*IndexUpdatesResponse, error) {
	m := new(IndexUpdatesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storeClient) DeindexTicket(ctx context.Context, in *DeindexTicketRequest, opts ...grpc.CallOption) (*DeindexTicketResponse, error) {
	out := new(DeindexTicketResponse)
	err := c.cc.Invoke(ctx, "/api.Store/DeindexTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) CreateTicket(ctx context.Context, in *CreateTicketRequest, opts ...grpc.CallOption) (*CreateTicketResponse, error) {
	out := new(CreateTicketResponse)
	err := c.cc.Invoke(ctx, "/api.Store/CreateTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) AssignTickets(ctx context.Context, in *AssignTicketsRequest, opts ...grpc.CallOption) (*AssignTicketsResponse, error) {
	out := new(AssignTicketsResponse)
	err := c.cc.Invoke(ctx, "/api.Store/AssignTickets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) AssignmentSubscribe(ctx context.Context, opts ...grpc.CallOption) (Store_AssignmentSubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Store_serviceDesc.Streams[1], "/api.Store/AssignmentSubscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &storeAssignmentSubscribeClient{stream}
	return x, nil
}

type Store_AssignmentSubscribeClient interface {
	Send(*AssignmentSubscribeRequest) error
	Recv() (*AssignmentSubscribeResponse, error)
	grpc.ClientStream
}

type storeAssignmentSubscribeClient struct {
	grpc.ClientStream
}

func (x *storeAssignmentSubscribeClient) Send(m *AssignmentSubscribeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storeAssignmentSubscribeClient) Recv() (*AssignmentSubscribeResponse, error) {
	m := new(AssignmentSubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StoreServer is the server API for Store service.
type StoreServer interface {
	IndexUpdates(*IndexUpdatesRequest, Store_IndexUpdatesServer) error
	DeindexTicket(context.Context, *DeindexTicketRequest) (*DeindexTicketResponse, error)
	CreateTicket(context.Context, *CreateTicketRequest) (*CreateTicketResponse, error)
	AssignTickets(context.Context, *AssignTicketsRequest) (*AssignTicketsResponse, error)
	AssignmentSubscribe(Store_AssignmentSubscribeServer) error
}

func RegisterStoreServer(s *grpc.Server, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

func _Store_IndexUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(IndexUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoreServer).IndexUpdates(m, &storeIndexUpdatesServer{stream})
}

type Store_IndexUpdatesServer interface {
	Send(*IndexUpdatesResponse) error
	grpc.ServerStream
}

type storeIndexUpdatesServer struct {
	grpc.ServerStream
}

func (x *storeIndexUpdatesServer) Send(m *IndexUpdatesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Store_DeindexTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeindexTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).DeindexTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Store/DeindexTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).DeindexTicket(ctx, req.(*DeindexTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_CreateTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).CreateTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Store/CreateTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).CreateTicket(ctx, req.(*CreateTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_AssignTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).AssignTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Store/AssignTickets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).AssignTickets(ctx, req.(*AssignTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_AssignmentSubscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StoreServer).AssignmentSubscribe(&storeAssignmentSubscribeServer{stream})
}

type Store_AssignmentSubscribeServer interface {
	Send(*AssignmentSubscribeResponse) error
	Recv() (*AssignmentSubscribeRequest, error)
	grpc.ServerStream
}

type storeAssignmentSubscribeServer struct {
	grpc.ServerStream
}

func (x *storeAssignmentSubscribeServer) Send(m *AssignmentSubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storeAssignmentSubscribeServer) Recv() (*AssignmentSubscribeRequest, error) {
	m := new(AssignmentSubscribeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeindexTicket",
			Handler:    _Store_DeindexTicket_Handler,
		},
		{
			MethodName: "CreateTicket",
			Handler:    _Store_CreateTicket_Handler,
		},
		{
			MethodName: "AssignTickets",
			Handler:    _Store_AssignTickets_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IndexUpdates",
			Handler:       _Store_IndexUpdates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AssignmentSubscribe",
			Handler:       _Store_AssignmentSubscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/store.proto",
}
