# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.stresstest.masterName }}
  namespace: {{ .Release.Namespace }}
  annotations: {{- include "openmatch.chartmeta" . | nindent 4 }}
  labels:
    app: {{ template "openmatch.name" . }}
    component: locust-master
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ template "openmatch.name" . }}
    component: locust-master
  type: {{ coalesce .Values.global.kubernetes.service.portType .Values.stresstest.portType }}
  ports:
  - name: loc-master-web
    port: 8089
    targetPort: loc-master-web
    protocol: TCP
  - name: loc-master-p1
    port: 5557
    targetPort: loc-master-p1
    protocol: TCP
  - name: loc-master-p2
    port: 5558
    targetPort: loc-master-p2
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {{- include "openmatch.chartmeta" . | nindent 4 }}
  name: {{ .Values.stresstest.masterName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "openmatch.name" . }}
    component: locust-master
    release: {{ .Release.Name }}
spec:
  replicas: 1 # We only need one master
  selector:
    matchLabels:
      app: {{ template "openmatch.name" . }}
      component: locust-master
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      annotations:
        {{- include "openmatch.chartmeta" . | nindent 8 }}
      labels:
        app: {{ template "openmatch.name" . }}
        component: locust-master
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.kubernetes.serviceAccount }}
      containers:
      - name: {{ .Values.stresstest.masterName }}
        image: "{{ coalesce .Values.global.image.registry .Values.image.registry }}/{{ .Values.stresstest.image}}:{{ coalesce .Values.global.image.tag .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: loc-master-web
          containerPort: 8089
          protocol: TCP
        - name: loc-master-p1
          containerPort: 5557
          protocol: TCP
        - name: loc-master-p2
          containerPort: 5558
          protocol: TCP
{{- if .Values.stresstest.noweb }}
        env:
        - name: NO_WEB
          value: "{{ .Values.stresstest.noweb }}"
        - name: GCP_PROJECT
          value: "{{ .Values.global.gcpProjectId }}"
{{- end }}
        command: ["python3"]
        # TODO: template the secure mode
        args:
        - "./locust"
        - "-f"
        - "./frontend.py"
        - "--host=http://{{ .Values.frontend.hostName }}:{{ .Values.frontend.httpPort }}"
        - "--master"
{{- if .Values.stresstest.noweb }}
        - "--no-web"
        - "-c{{ .Values.stresstest.clients }}"
        - "-r{{ .Values.stresstest.rate }}"
        - "-t{{ .Values.stresstest.duration }}"
        - "--expect-slaves={{ .Values.stresstest.replicas }}"
        - "--csv=stress_user{{ .Values.stresstest.clients }}"
{{- end }}
