# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  # This annotation is not critical to security. 
  # If the Cloud IAM binding does not exist, this annotation does not allow the Pod to use the GSA.
  # Ref: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
  annotations:
    iam.gke.io/gcp-service-account: stress-test-uploader@{{ .Values.global.gcpProjectId }}.iam.gserviceaccount.com
  name: {{ .Values.kubernetes.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "openmatch.name" . }}
    release: {{ .Release.Name }}
