# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

dependencies:
  - name: open-match-core
    version: 0.0.0-dev
    condition: open-match-core.enabled
    repository: "file://./subcharts/open-match-core"
  - name: open-match-demo
    version: 0.0.0-dev
    condition: open-match-demo.enabled
    repository: "file://./subcharts/open-match-demo"
  - name: open-match-telemetry
    version: 0.0.0-dev
    condition: open-match-telemetry.enabled
    repository: "file://./subcharts/open-match-telemetry"
  - name: open-match-customize
    version: 0.0.0-dev
    condition: open-match-customize.enabled
    repository: "file://./subcharts/open-match-customize"
  - name: open-match-test
    version: 0.0.0-dev
    condition: open-match-test.enabled
    repository: "file://./subcharts/open-match-test"

